# Generated by Django 5.2.7 on 2025-12-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('photo', models.ImageField(upload_to='profile_images/', verbose_name='Profil Fotoğrafı')),
                ('role', models.CharField(choices=[('admin', 'Yönetici'), ('student', 'Ogrenci')], default='student', max_length=10)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
