# Generated by Django 5.2.14 on 2026-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Student ID'),
            preserve_default=False,
        ),
    ]
