# Generated by Django 5.2.7 on 2026-06-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_courses_alter_student_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
