# Generated by Django 5.2.7 on 2026-05-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('start_time', models.TimeField(verbose_name='Ders Başlangıç Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sistem Açık mı?')),
            ],
            options={
                'verbose_name': 'Ders Ayarı',
                'verbose_name_plural': 'Ders Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('time_in', models.TimeField(auto_now_add=True, verbose_name='Giriş Saati')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.student', verbose_name='Öğrenci')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.course', verbose_name='İlgili Ders')),
            ],
            options={
                'verbose_name': 'Yoklama Kaydı',
                'verbose_name_plural': 'Yoklama Kayıtları',
            },
        ),
    ]
