# Generated by Django 5.2.14 on 2026-06-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_remove_student_emp_id_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('start_time', models.TimeField(verbose_name='Ders Başlangıç Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sistem Açık mı?')),
            ],
            options={
                'verbose_name': 'Ders Ayarı',
                'verbose_name_plural': 'Ders Ayarları',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Yoklama Kaydı', 'verbose_name_plural': 'Yoklama Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(auto_now_add=True, verbose_name='Giriş Saati'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.course', verbose_name='İlgili Ders'),
        ),
    ]
