# Generated by Django 5.2.7 on 2026-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_course_alter_attendance_options_and_more'),
        ('students', '0002_remove_student_emp_id_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students.student'),
        ),
    ]
