# Generated by Django 5.2.7 on 2026-06-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_course_students'),
        ('attendance', '0004_alter_attendance_options_alter_course_options_and_more'),
    ]

    operations = [
    ]
