# Generated by Django 5.2.7 on 2026-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_merge_20260603_1814'),
        ('students', '0004_remove_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='registered_courses', to='students.student'),
        ),
    ]
