# Generated by Django 5.2.7 on 2026-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Check In Time'),
        ),
    ]
