# Generated by Django 5.2.7 on 2026-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, verbose_name='Day of the Week'),
        ),
    ]
